### ISSUE TITLE
Running STEMMUS_SCOPE sensitivity analysis on Snellius with parallel computing

### ISSUE THREAD

**Issue by Crystal-szj** [EcoExtreML/STEMMUS_SCOPE#187]
@SarahAlidoost Hi Sarah, 

I hope this message finds you well.
I want to do a sensitivity analysis on STEMMUS_SCOPE by setting different sets of parameters (run the model 380 times). I would like to utilize parallel computing to finish this part.

To begin, I have created a new executable file via [STEMMUS_SCOPE_SS_exe.m](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/src/STEMMUS_SCOPE_SS_exe.m) that requires two input parameters: one for the config file (`config_file`) and the other for the parameters (`parameter_setting_file`). The Matlab code portion has been completed.

My intention is to utilize the existing _run_STEMMUS_SCOPE_in_Snellius_ framework. If I understand correctly, I need to modify the `run_model.py` file to iterate through the input parameter file instead of the input forcing data for 170 sites.

The _pystemmusscope_ environment is activated. Now I have a couple of questions:
1.	In the `run_model.py` file, see [here](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEcoExtreML%2FSTEMMUS_SCOPE%2Fblob%2Fmain%2Frun_model_on_snellius%2Frun_model.py%23L23&data=05%7C01%7Cz.song%40utwente.nl%7C65a5e8b66a034cbcf2c808db73bb2584%7C723246a1c3f543c5acdc43adb404ac4d%7C0%7C0%7C638231019846438914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ph2Jku1JFQSPoYuMFPG%2B4n9AyRx6JGB7ElO1G6lOKTY%3D&reserved=0), we need to create an instance of the model. However, the `parameter_file` is not an input for the [StemmusScope class](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/main/PyStemmusScope/stemmus_scope.py#L96). Does this mean I need to modify the StemmusScope class in 'pystemmusscope' package and reinstall the package? 
2.	Since the `run_model.py` requires the input of `job_id`, is it possible for me to test this modified version on my local computer to ensure there are no bugs before submitting it to Snellius? I'm not sure how to solve this in the development phase.

Please let me know if any information need be provided. I would greatly appreciate it if you could share your experience and provide guidance on how to address these questions.

Best regards,
Zengjing

**Comment by SarahAlidoost** [comment]
@Crystal-szj nice job in creating the issue :+1: , thanks. Here answers:

1. You dont need a new function `STEMMUS_SCOPE_SS_exe.m` that accepts two input variables. Instead, follow these steps: 
 - [ ] add the path of `parameter_setting_file` to your [`config_file`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/config_file_linux373.txt); For example at the end of the file, add a new line `ParameterSettingsPath = ../../O2_para_lists/para_value_SS001.xlsx`. 
 - [ ]  change the `io.read_config(CFG)` to get the path, for example [`[DataPaths, forcingFileName, numberOfTimeSteps, startDate, endDate, gsOption, phsOption, RunningMessages, ParameterSettingsPath] = io.read_config(CFG);`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/35a8162b15332d136b52a4ed1b81c5b301a159e0/src/STEMMUS_SCOPE_SS.m#L80C109-L80C128). 
 - [ ] then use the variable in your script, e.g. `para_sens = readtable(ParameterSettingsPath);`
 
So, you need to move things around in `STEMMUS_SCOPE_SS.m`. If the path to `parameter_setting_file` changes everytime you run the model, in the `run_model.py` file, write a small function that reads the `config_file` and writes it again with a new path to  `parameter_setting_file`.

**Comment by SarahAlidoost** [comment]
2. the variable `job_id` is only used to write the log file. You can create a `run_model_local.py` file and remove` job_id`. Then use  `run_model_local.py` locally.

**Comment by SarahAlidoost** [comment]
Just to give you ideas about reading and writing config_file in python, here are some examples [read_config](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/fc1513ad87624d2568abfe49162e1b101de5997c/PyStemmusScope/config_io.py#L19-L38) and [update_config](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/fc1513ad87624d2568abfe49162e1b101de5997c/PyStemmusScope/config_io.py#L133-L166). Use them as an example, you need to write your own functions.

**Comment by Crystal-szj** [comment]
> 2. the variable `job_id` is only used to write the log file. You can create a `run_model_local.py` file and remove` job_id`. Then use  `run_model_local.py` locally.

@SarahAlidoost  Hi, Sarah, many thanks for your suggestions. I commented out the `job_id` part and `Argparse` part, and tried running [`run_model_local.py`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/run_model_local.py) on my computer in Pycharm. I'm testing with a test file at _AR-SLu_, but I get an error when I run this line [here](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/run_model_local.py#L40).  The `exit_code` is 1 instead of  0 or 139, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/blob/main/PyStemmusScope/stemmus_scope.py#L79). I copied the error message here:

>D:\software\Anaconda3\envs\pystemmusscope\python.exe F:\P1\sensitivitiy_analysis_CLM5_scheme\STEMMUS_SCOPE_SS\run_model_on_snellius\run_model_local.py 
D:\software\Anaconda3\envs\pystemmusscope\lib\site-packages\xarray\core\accessor_dt.py:72: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  values_as_series = pd.Series(values.ravel(), copy=False)
Traceback (most recent call last):
  File "F:\P1\sensitivitiy_analysis_CLM5_scheme\STEMMUS_SCOPE_SS\run_model_on_snellius\run_model_local.py", line 93, in <module>
    run_model_local(0)
  File "F:\P1\sensitivitiy_analysis_CLM5_scheme\STEMMUS_SCOPE_SS\run_model_on_snellius\run_model_local.py", line 40, in run_model_local
    model_log = model.run()
  File "D:\software\Anaconda3\envs\pystemmusscope\lib\site-packages\PyStemmusScope\stemmus_scope.py", line 206, in run
    result = _run_sub_process(args, None)
  File "D:\software\Anaconda3\envs\pystemmusscope\lib\site-packages\PyStemmusScope\stemmus_scope.py", line 85, in _run_sub_process
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['F:\\P1\\sensitivitiy_analysis_CLM5_scheme\\STEMMUS_SCOPE_SS\\run_model_on_snellius\\exe\\STEMMUS_SCOPE F:\\P1\\sensitivitiy_analysis_CLM5_scheme\\STEMMUS_SCOPE_SS\\run_model_on_snellius\\input\\AR-SLu_2023-06-26-1225\\AR-SLu_2023-06-26-1225_config.txt']' returned non-zero exit status 1.

>Process finished with exit code 1

Could you please help me to figure out what's wrong here? Please let me know if more information is needed. Thanks very much.

**Comment by SarahAlidoost** [comment]
@Crystal-szj there are several things to check:

- the version of pystemmusscope and stemmus_scope, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/releases/tag/v0.3.0). 
- if you are running exe file with matlab runtime, you might need to set `LD_LIBRARY_PATH`, see the [documentation](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_in_notebook/)
- `model.setup()` genertaes input data in an input directory. Could you check if you can run your stemmus_scope code using the input data with matlab? It should return more info about errors, if any. 
- check if generated exe file works.

**Comment by Crystal-szj** [comment]
@SarahAlidoost Many thanks for your advice.
- About the version of pystemmusscope. I use the latest version of `pystemmusscope`. The version is 0.3.0.
- I set the `LD_LIBRARY_PATH` accordingly. However, I'm running and debugging the Python code `run_model.py` and currently not use the Matlab runtime.
- After running `model.setup()`, yes, it created an input directory including but without the `.nc` file. I use the `config_file` it generated in the input directory, and netcdf file in `InputPath`, it works.
- About the generated exe file: In my case, I create an executable file named [`STEMMUS_SCOPE_SS.exe`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/exe/STEMMUS_SCOPE_SS.exe), and the config file named [`config_file_snellius_sensitivity_analysis`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/config_file_snellius_sensitivity_analysis.txt).
I can run the exe file via python console
```python
import subprocess
subprocess.run(['.\exe\STEMMUS_SCOPE_SS.exe','.\config_file_snellius_sensitivity_analysis.txt'])
```
or WSL terminal
```
./exe/STEMMUS_SCOPE_SS.exe ./config_file_snellius_sensitivity_analysis.txt
```
Both of above commands work well. I think the exe file works.

However, when I run [`model.run()`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/run_model_local.py#L40), the program break and doesn't execute continuously.

**Comment by Crystal-szj** [comment]
The above problem may cause by the different operating systems (e.g. Linux and Windows). The [documentation](https://pystemmusscope.readthedocs.io/en/latest/notebooks/run_model_in_notebook/) works well on the Linux system, but failed on WSL [see here](https://github.com/EcoExtreML/STEMMUS_SCOPE_Processing/issues/39). In addition, the executable file generated by different systems may not be compatible. It's better to regenerate the executable file when run it on a new system.

**Comment by SarahAlidoost** [comment]
> 1. To submit the task to Snellius, I used the [`run_stemmus_scope_snellius.sh`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/run_stemmus_scope_snellius.sh). 

I see that you commented out the [`loop for`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/5d19bf964e35a8d677ddd59f24d74b73f87538a2/run_model_on_snellius/run_stemmus_scope_snellius.sh#L39-L49). Also, the variables `ncores`, `i`, and `k` are not used in your code. The loop is exactly the place where parallel execution is implemented. I am not sure if you saw the surf documentation that I have already sent to Qianqian, here are the links
https://servicedesk.surf.nl/wiki/display/WIKI/Methods+of+parallelization
https://servicedesk.surf.nl/wiki/display/WIKI/Example+job+scripts#Examplejobscripts-Singlenode,concurrentprogramsonthesamenode(CPUandGPU)

**Comment by Crystal-szj** [comment]
> I see that you commented out the [`loop for`](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/5d19bf964e35a8d677ddd59f24d74b73f87538a2/run_model_on_snellius/run_stemmus_scope_snellius.sh#L39-L49). Also, the variables `ncores`, `i`, and `k` are not used in your code. The loop is exactly the place where parallel execution is implemented. 

Thanks for your prompt response and links. I understand your approach, where each site is assigned to a separate core for parallel execution. That enables the completion of 170 sites in six rounds, with 32 sites processed per round.

However, considering the need for one task to run on a single core, as both you and Qianqian mentioned, I believe I should follow the 'parallel execution of serial programs' approach, where parallelism is not programmed into the STEMMUS_SCOPE model. According to this method, if I submit one task, only one CPU should be utilized, and if I submit ten tasks, ten CPUs should work concurrently.

I noticed from the above screenshot that multiple cores were active, even though I just submitted only one task. Does this indicate the presence of parallelism within the executable file? My question is whether I should ensure "one task one CPU" or whether I can overlook this issue and proceed with using the [loop for](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/5d19bf964e35a8d677ddd59f24d74b73f87538a2/run_model_on_snellius/run_stemmus_scope_snellius.sh#L39-L49) to run the 380 cases.

Thanks again for your guidance and expertise.

**Comment by SarahAlidoost** [comment]
> According to this method, if I submit one task, only one CPU should be utilized, and if I submit ten tasks, ten CPUs should work concurrently.

No, this is not the case except you tell the computer to run ten tasks on ten cores. It means that you should implement a method of parallelization, e.g. the [loop for](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/run_model_on_snellius_sensitivity_analysis.py) with the parameter `wait` and `&` .  You have to figure out how many cores are used by one task (your code). It is okay if your code needs more than one core. But you need this information i.e. number of cores, memory usage, ... to be able to implement a method of parallelization.

**Comment by SarahAlidoost** [comment]
> However, considering the need for one task to run on a single core, as both you and Qianqian mentioned, I believe I should follow the 'parallel execution of serial programs' approach, where parallelism is not programmed into the STEMMUS_SCOPE model. According to this method, if I submit one task, only one CPU should be utilized, and if I submit ten tasks, ten CPUs should work concurrently.

your code is different than Qianqian's code and does not use many Python libraries. If you are just running stemmus_scope, it should use only one core except that your stemmus_scope is very different than the one in the [main branch](https://github.com/EcoExtreML/STEMMUS_SCOPE).  If this is not the case, please check the code to [build exe file](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2e13e98fe506c03b6c9b6c20b4f17db37c71dff4/run_model_on_snellius/exe/build_stemmus_scope_exe.sh#L25-L26) and make sure that the argument `-R singleCompThread` is set.

**Comment by Crystal-szj** [comment]
> If you are just running stemmus_scope, it should use only one core except that your stemmus_scope is very different than the one in the [main branch](https://github.com/EcoExtreML/STEMMUS_SCOPE). If this is not the case, please check the code to [build exe file](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2e13e98fe506c03b6c9b6c20b4f17db37c71dff4/run_model_on_snellius/exe/build_stemmus_scope_exe.sh#L25-L26) and make sure that the argument `-R singleCompThread` is set.

Thanks for your reply. I uncommented the `loop for` and used it to submit 2 cases to do the test run, see the [run_stemmus_scope_snellius.sh](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/run_stemmus_scope_snellius.sh). At the time being, apart from a few seconds, typically only "two cores" are active concurrently. However, sometimes the CPU usage per core exceeds 100% (please see the screenshot). It's worth noting that I have set the argument "-R singleCompThread" when building the executable file [see here](https://github.com/EcoExtreML/STEMMUS_SCOPE_sensitivity_analysis/blob/sensitivity_analysis_CLM5_scheme/run_model_on_snellius/exe/build_stemmus_scope_exe.sh#L26C1-L26C126). 

I would like to inquire whether this occasional CPU usage exceeding 100% should be a cause for concern. If it is not, I can proceed with using the for loop to run the 380 cases as initially planned.
![image](https://github.com/EcoExtreML/STEMMUS_SCOPE/assets/94700881/87ccc933-3a19-49c1-b423-4cd7ef8581e2)
![image](https://github.com/EcoExtreML/STEMMUS_SCOPE/assets/94700881/e4be4fcb-6ddb-4125-9760-35723aba1381)

**Comment by Crystal-szj** [comment]
> If you are just running stemmus_scope, it should use only one core except that your stemmus_scope is very different than the one in the [main branch](https://github.com/EcoExtreML/STEMMUS_SCOPE). If this is not the case, please check the code to [build exe file](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2e13e98fe506c03b6c9b6c20b4f17db37c71dff4/run_model_on_snellius/exe/build_stemmus_scope_exe.sh#L25-L26) and make sure that the argument `-R singleCompThread` is set.

The STEMMUS_SCOPE version I used is based on version 1.1.9. And I  added the plant hydraulics part as a separate function. I'd like to clarify that I have not utilized any parallel computer packages such as `parfor` within my function. The execution is currently running in a sequential manner.

If you have any further questions or require more details, please let me know. Thanks for your support.
